require('modules/nvim-tree')
require('modules/treesitter')
require('modules/toggleterm')
require('modules/telescope')
require('modules/lualine')
require('modules/material-theme')
require('modules/nvim-cmp')
