#!/usr/bin/env bash

set -euo pipefail
DIR=$(cd "$(dirname "${BASH_SOURCE[0]}")" && pwd)

TARGET_HOST="${1:-}"
TARGET_USER="${2:-paul}"

if [ "$(id -u)" -eq 0 ]; then
  echo "ERROR! $(basename "${0}") should be run as a regular user"
  exit 1
fi

if [[ -z "$TARGET_HOST" ]]; then
  echo "ERROR! $(basename "${0}") requires a hostname as the first argument"
  exit 1
fi

if [ ! -e "hosts/${TARGET_HOST}/disks.nix" ]; then
  echo "ERROR! $(basename "${0}") could not find the required hosts/${TARGET_HOST}/disks.nix"
  exit 1
fi

# Check if the machine we're provisioning expects a keyfile to unlock a disk.
# If it does, generate a new key, and write to a known location.
if grep -q "data.keyfile" "hosts/${TARGET_HOST}/disks.nix"; then
  echo -n "$(head -c32 /dev/random | base64)" >/tmp/data.keyfile
fi

echo "WARNING! The disks in ${TARGET_HOST} are about to get wiped"
echo "         NixOS will be re-installed"
echo "         This is a destructive operation"
echo
read -p "Are you sure? [y/N]" -n 1 -r
echo
if [[ $REPLY =~ ^[Yy]$ ]]; then
  sudo true

  sudo nix --experimental-features "nix-command flakes" run github:nix-community/disko/latest -- --mode destroy,format,mount "hosts/${TARGET_HOST}/disks.nix" --yes-wipe-all-disks

  sudo nixos-install --flake ".#${TARGET_HOST}"

  # Rsync my nix-config to the target install
  mkdir -p "/mnt/home/${TARGET_USER}/.dotfiles"
  rsync -a --delete "${DIR}/.." "/mnt/home/${TARGET_USER}"

  # Setup home-manager for the target user. (Change to nix-instance using nixos-enter, change user and run home-manager switch)
  echo "echo 'home-manager switch --flake /home/${TARGET_USER}/.dotfiles' | sudo -u ${TARGET_USER} bash" | sudo nixos-enter

  # If there is a keyfile for a data disk, put copy it to the root partition and
  # ensure the permissions are set appropriately.
  if [[ -f "/tmp/data.keyfile" ]]; then
    sudo cp /tmp/data.keyfile /mnt/etc/data.keyfile
    sudo chmod 0400 /mnt/etc/data.keyfile
  fi
fi
