#!/bin/sh

HOSTNAME=$(uname -n)

# Update Package Listing
if (command -v pacman &> /dev/null); then
    pacman -Qqen > "$HOME/.config/yadm/packages##os.Linux,h.$HOSTNAME"
fi

# Update Brew Listing
if (command -v brew &> /dev/null); then
    cd $HOME/.config/yadm && brew bundle dump --quiet --force && mv Brewfile 'packages##os.Darwin' && rm Brewfile.lock.json 2> /dev/null
fi

# Update Submodules
yadm submodule update --recursive --remote
