#!/bin/sh

# Firefox
if (command -v firefox &> /dev/null); then 
	for path in ~/.mozilla/firefox/*-release/; do
		mkdir $path/chrome/ 2&>/dev/null
		if ! (test -f $path/chrome/userChrome.css); then
			echo '[Firefox] Linking user css to' $path
			ln -s ~/.config/firefox/* $path/chrome
		fi
	done
fi

# Librewolf
if (command -v librewolf &> /dev/null); then 
	for path in ~/.librewolf/*-release/; do
		mkdir $path/chrome/ 2&>/dev/null
		if ! (test -f $path/chrome/userChrome.css); then
			echo '[Librewolf] Linking user css to' $path
			ln -s ~/.config/firefox/* $path/chrome
		fi
	done
fi

# Update Package Listing
pacman -Qe | cut -f 1 -d " " > $HOME/.config/yadm/aur_packages.txt

# Update Submodules
yadm submodule update --recursive --remote